In [1]:
from clarkewright import *  

In [2]:
routes = [[0,1,0],[0,2,3,4,0]]

In [3]:
half_mat = np.array([[-1,10,12,15,7],[-1,-1,5,12,11],[-1,-1,-1,7,9],[-1,-1,-1,-1,10],[-1,-1,-1,-1,-1]])

In [4]:
total_mat = np.copy(half_mat)
print(total_mat)
total_mat = np.transpose(total_mat) + half_mat
print(total_mat)

[[-1 10 12 15  7]
 [-1 -1  5 12 11]
 [-1 -1 -1  7  9]
 [-1 -1 -1 -1 10]
 [-1 -1 -1 -1 -1]]
[[-2  9 11 14  6]
 [ 9 -2  4 11 10]
 [11  4 -2  6  8]
 [14 11  6 -2  9]
 [ 6 10  8  9 -2]]


In [5]:
total_cost = calculate_cost(routes, half_mat)

[[ 0 10 12 15  7]
 [ 0  0  5 12 11]
 [ 0  0  0  7  9]
 [ 0  0  0  0 10]
 [ 0  0  0  0  0]]
[[ 0 10 12 15  7]
 [10  0  5 12 11]
 [12  5  0  7  9]
 [15 12  7  0 10]
 [ 7 11  9 10  0]]


In [6]:
print(total_cost)  

56


In [ ]:
def calculate_cost(routes, half_mat):
    #route에 따른 cost 리턴하기?  
    
    #half matrix를 전체 matrix로 확장(인접하게)
    #각 노드들 간의 최단 거리 행렬 
    changed_half_mat = np.copy(half_mat)
    for i in range(len(changed_half_mat)):
        for j in range(len(changed_half_mat)):
            if changed_half_mat[i,j] == -1:
                changed_half_mat[i,j] = 0
    
    print(changed_half_mat)
    
    total_mat = changed_half_mat + np.transpose(changed_half_mat) 
    print(total_mat)
    #routes에 따라서 cost 계산
    total_cost = 0
    
    for route_idx, route in enumerate(routes):
        for i in range(len(route)-1):  
            total_cost += total_mat[route[i],route[i+1]] 
    
    return total_cost