In [13]:
from clarkewright import *

## Information of Functions in clarkewright.py  

- half_mat, t_mat, demand, is_const = initialize(N, is_constraint)  

- net_saving_mat = calculate_net_saving(half_mat, N)   

- t_mat, adjacency, net_saving_mat, cells = max_net_saving(half_mat, t_mat, net_saving_mat, demand, is_constraint,  Q)    
    - adjacency = make_adjacency_mat(t_mat)  
    - tmp_t_mat = change_t_mat(t_mat, i, j)   
    - available_flag = check_routes(adjacency, i, j)
        - routes = search_all_route(adjacency)  
    - flag = check_capacity(adjacency, demand, Q)
        - routes = search_all_route(adjacency)  


## Examples

### 1. Unconstraint Problem of ppt  

In [33]:
N = 5 # number of nodes  
Q = 10 #각 vehicle capacity  
is_constraint = False
half_mat, t_mat, demand, is_constraint = initialize(N, is_constraint)   
print("half_mat")
print(half_mat)
print()
print("t_mat")
print(t_mat)
print()
net_saving_mat = calculate_net_saving(half_mat, N)
print("net_saving_mat")
print(net_saving_mat) 
print()
adjacency = make_adjacency_mat(t_mat)
routes = search_all_route(adjacency)
print("routes")
print(routes)
print()



###################
print("loop start") 
print()
count = 0
while(True):
    count += 1  
    print("iteration:{}".format(count))
    t_mat, adjacency, net_saving_mat, cells= max_net_saving(half_mat, t_mat, net_saving_mat, demand, is_constraint,  Q)
    #print(cells)
    #print(net_saving_mat)
    routes = search_all_route(adjacency)  
    print(routes)
    
    if len(cells) == 0 or len(routes) == 1:
        print("loop end")
        break 
        

half_mat
[[-1 10 12 15  7]
 [-1 -1  5 12 11]
 [-1 -1 -1  7  9]
 [-1 -1 -1 -1 10]
 [-1 -1 -1 -1 -1]]

t_mat
[[0 2 2 2 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

net_saving_mat
[[-1 -1 -1 -1 -1]
 [-1 -1 17 13  6]
 [-1 -1 -1 20 10]
 [-1 -1 -1 -1 12]
 [-1 -1 -1 -1 -1]]

routes
[[0, 1, 0], [0, 2, 0], [0, 3, 0], [0, 4, 0]]

loop start

iteration:1
False
max_i: 2
max_j: 3
[[0, 1, 0], [0, 2, 3, 0], [0, 4, 0]]
iteration:2
False
max_i: 1
max_j: 2
[[0, 1, 2, 3, 0], [0, 4, 0]]
iteration:3
False
max_i: 3
max_j: 4
[[0, 1, 2, 3, 4, 0]]
loop end


### 2. Constraint Problem of ppt 

In [35]:
N = 5 # number of nodes  
Q = 10 #각 vehicle capacity  
is_constraint = True
half_mat, t_mat, demand, is_constraint = initialize(N, is_constraint)   
print("half_mat")
print(half_mat)
print()
print("t_mat")
print(t_mat)
print()
net_saving_mat = calculate_net_saving(half_mat, N)
print("net_saving_mat")
print(net_saving_mat) 
print()
adjacency = make_adjacency_mat(t_mat)
routes = search_all_route(adjacency)
print("routes")
print(routes)
print()



####################
print("loop start") 
print()
count = 0
while(True):
    count += 1  
    print("iteration:{}".format(count))
    t_mat, adjacency, net_saving_mat, cells= max_net_saving(half_mat, t_mat, net_saving_mat, demand, is_constraint,  Q)
    #print(cells)
    #print(net_saving_mat)
    routes = search_all_route(adjacency)  
    print("routes")
    print(routes)
    print()
    if len(cells) == 0 or len(routes) == 1:
        print("loop end")
        break 


half_mat
[[-1 10 12 15  7]
 [-1 -1  5 12 11]
 [-1 -1 -1  7  9]
 [-1 -1 -1 -1 10]
 [-1 -1 -1 -1 -1]]

t_mat
[[0 2 2 2 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

net_saving_mat
[[-1 -1 -1 -1 -1]
 [-1 -1 17 13  6]
 [-1 -1 -1 20 10]
 [-1 -1 -1 -1 12]
 [-1 -1 -1 -1 -1]]

routes
[[0, 1, 0], [0, 2, 0], [0, 3, 0], [0, 4, 0]]

loop start

iteration:1
True
max_i: 2
max_j: 3
routes
[[0, 1, 0], [0, 2, 3, 0], [0, 4, 0]]

iteration:2
True
max_i: 3
max_j: 4
routes
[[0, 1, 0], [0, 2, 3, 4, 0]]

iteration:3
True
max_i: -1
max_j: -1
routes
[[0, 1, 0], [0, 2, 3, 4, 0]]

loop end


## Check search_all_route(adjacency) 

### Case 1  

![](case1.png)

In [27]:
#case1 - single route 
adjacency = np.array([[0,1,1,0,0],[1,0,0,0,1],[1,0,0,1,0],[0,0,1,0,1],[0,1,0,1,0]])
routes = search_all_route(adjacency) 
print(routes) 

[[0, 1, 4, 3, 2, 0]]


### Case 2  
![](case2.png)  

In [28]:
#case2
adjacency = np.array([[0,1,0,2,1],[1,0,1,0,0],[0,1,0,0,1],[2,0,1,0,1],[1,0,1,0,0]])
routes = search_all_route(adjacency) 
print(routes) 

[[0, 1, 2, 4, 0], [0, 3, 0]]


### Case 3   
![](case3.png)  

In [29]:
#case3
adjacency = np.array([[0,2,2,2,2],[2,0,0,0,0],[2,0,0,0,0],[2,0,0,0,0],[2,0,0,0,0]])
routes = search_all_route(adjacency)
print(routes)

[[0, 1, 0], [0, 2, 0], [0, 3, 0], [0, 4, 0]]


### Case 4   
![](case4.png)  

In [30]:
#case4
adjacency = np.array([[0,1,1,0,2],[1,0,0,1,0],[1,0,0,1,0],[0,1,1,0,0],[2,0,0,0,0]])
routes = search_all_route(adjacency)
print(routes)  

[[0, 1, 3, 2, 0], [0, 4, 0]]


### Case 5  
![](case5.png)  

In [31]:
#case5 - single route
adjacency = np.array([[0,0,0,1,1],[0,0,1,0,1],[0,1,0,1,0],[1,0,1,0,0],[1,1,0,0,0]])
routes = search_all_route(adjacency) 
print(routes)

[[0, 3, 2, 1, 4, 0]]
